# actionlint configuration
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

self-hosted-runner:
  labels:
    # Blacksmith CI runners
    - blacksmith-8vcpu-ubuntu-2404
    - blacksmith-8vcpu-windows-2025
    - blacksmith-16vcpu-ubuntu-2404
    - blacksmith-16vcpu-windows-2025
    - blacksmith-16vcpu-ubuntu-2404-arm

# Ignore patterns for known issues
paths:
  .github/workflows/**/*.yml:
    ignore:
      # Ignore shellcheck warnings (we run shellcheck separately)
      - "shellcheck reported issue.+"
      # Ignore intentional if: false for disabled jobs
      - 'constant expression "false" in condition'
      # actionlint's built-in runner label allowlist lags Blacksmith additions.
      - 'label "blacksmith-16vcpu-[^"]+" is unknown\.'
